import type { WordSetData } from "../wordSetModels";

export const wordsetCompSci: WordSetData = {
  name: "Computer Science Terms",
  category: "sciences",
  description: "Terminology related to computer science and programming.",
  language: "en",
  words: [
    "Algorithm",
    "Array",
    "Artificial Intelligence",
    "ASCII",
    "Binary",
    "Binary Search",
    "Big Data",
    "Bit",
    "Blockchain",
    "Boolean Logic",
    "Cache Memory",
    "Cloud Computing",
    "Code Optimization",
    "Compiler",
    "Computational Complexity",
    "Computer Architecture",
    "Computer Graphics",
    "Computer Network",
    "Concurrency",
    "Cryptography",
    "Cybersecurity",
    "Data Compression",
    "Data Mining",
    "Data Structure",
    "Database",
    "Debugging",
    "Deep Learning",
    "DNS",
    "Dynamic Programming",
    "Edge Computing",
    "Encryption",
    "Ethical Hacking",
    "Firewall",
    "Function",
    "Game Development",
    "Garbage Collection",
    "Graph Theory",
    "Hashing",
    "Heap Memory",
    "Human-Computer Interaction",
    "HTTP",
    "IoT",
    "IPv4",
    "IPv6",
    "JSON",
    "Kernel",
    "Lambda Function",
    "Machine Learning",
    "Microprocessor",
    "Multithreading",
    "Natural Language Processing",
    "Network Protocol",
    "Neural Network",
    "Object-Oriented Programming",
    "Operating System",
    "Polymorphism",
    "Quantum Computing",
    "Recursion",
    "Regular Expression",
    "Relational Database",
    "REST API",
    "Sorting Algorithm",
    "SQL",
    "TCP/IP",
    "Tree Structure",
    "Turing Machine",
    "Unicode",
    "URL",
    "Variable",
    "Virtual Machine",
    "Web Scraping",
    "XML",
    "Zero-Day (Vulnerability)",
    "JavaScript (Programming Language)",
    "C (Programming Language)",
    "C++ (Programming Language)",
    "Java (Programming Language)",
    "Python (Programming Language)",
    "Ruby (Programming Language)",
    "PHP (Programming Language)",
    "Swift (Programming Language)",
    "Go (Programming Language)",
    "Rust (Programming Language)",
    "Kotlin (Programming Language)",
    "Dart (Programming Language)",
    "Scala (Programming Language)",
    "Haskell (Programming Language)",
    "Perl (Programming Language)",
    "R (Programming Language)",
    "MATLAB (Programming Language)",
    "Assembly Language",
    "Terminal",
    "Version Control",
    "Agile Development",
    "Scrum",
    "Kanban",
    "DevOps",
    "API Gateway",
    "Load Balancing",
    "Containerization",
    "Microservices",
    "Serverless Computing",
    "Continuous Integration",
    "Continuous Deployment",
    "Unit Testing",
    "Integration Testing",
    "User Interface (UI)",
    "Responsive Design",
    "SEO (Search Engine Optimization)",
    "A/B Testing",
    "Open Source",
    "Sprint",
    "Data Visualization",
    "LLM (Large Language Model)",
    "Prompt Engineering",
    "Generative AI",
    "Localhost",
    "Frontend",
    "Backend",
    "Full Stack",
    "P vs NP",
    "Turing Test",
    "Abstraction",
    "Backtracking",
    "Breadth-First Search",
    "Depth-First Search",
    "Checksum",
    "Clustering",
    "Deadlock",
    "Digital Signal Processing",
    "Distributed Computing",
    "Dynamic Typing",
    "Edge Detection",
    "Finite State Machine",
    "Floating Point",
    "Instruction Set",
    "Interrupt",
    "Mutex",
    "Operating System Kernel",
    "Pipeline",
    "Priority Queue",
    "Race Condition",
    "Semaphore",
    "Spanning Tree",
    "Stateful Protocol",
    "Stateless Protocol",
    "Thread",
    "Throughput",
    "Tokenization",
  ]
}
