import type { WordSetData } from "../wordSetModels";

export const wordsetMedicine: WordSetData = {
  name: "Medical Terms",
  category: "sciences",
  description: "Terminology related to the medical field.",
  language: "en",
  words: [
    "Anatomy",
    "Physiology",
    "Histology",
    "Biochemistry",
    "Pharmacology",
    "Pathology",
    "Microbiology",
    "Immunology",
    "Epidemiology",
    "Genetics",
    "Embryology",
    "Neuroscience",
    "Cardiology",
    "Pulmonology",
    "Gastroenterology",
    "Hematology",
    "Endocrinology",
    "Nephrology",
    "Dermatology",
    "Ophthalmology",
    "Otolaryngology",
    "Orthopedics",
    "Rheumatology",
    "Pediatrics",
    "Geriatrics",
    "Oncology",
    "Psychiatry",
    "Radiology",
    "Surgery",
    "Anesthesiology",
    "Obstetrics",
    "Gynecology",
    "Urology",
    "Forensic Medicine",
    "Public Health",
    "Clinical Research",
    "Palliative Care",
    "Medical Ethics",
    "Biostatistics",
    "Electrocardiogram (ECG)",
    "Blood Pressure",
    "Diabetes Mellitus",
    "Hypertension",
    "Stroke",
    "Sepsis",
    "Trauma",
    "Wound Healing",
    "X-ray",
    "CT Scan",
    "MRI",
    "Ultrasound",
    "Vaccination",
    "Antibiotics",
    "Autoimmune Disease",
    "Cognitive Behavioral Therapy",
    "Placebo Effect",
    "Triage",
    "Metabolism",
    "Hormones",
    "Liver Function Test",
    "Kidney Function Test",
    "Toxicology",
    "Genetic Counseling",
    "Stem Cell Therapy",
    "Neurotransmitters",
    "Synapse",
    "Apoptosis",
    "Carcinogenesis",
    "Metastasis",
    "Biopsy",
    "Homeostasis",
    "Prognosis",
    "Oncogene",
    "Cytokines",
    "Phagocytosis",
    "Inflammation",
    "Arrhythmia",
    "Thrombosis",
    "Dementia",
    "Osteoporosis",
    "Dialysis",
    "Bronchoscopy",
    "Colonoscopy",
    "Endoscopy",
    "Intubation",
    "Defibrillation",
    "Hypothermia",
    "Hyperthermia",
    "Hypoxia",
    "Septicemia",
    "Pneumonia",
    "Meningitis",
    "Hepatitis",
    "Pancreatitis",
    "Arthritis",
    "Osteomyelitis",
    "Rhinitis",
    "Tonsillitis",
    "Bronchitis",
    "Appendicitis",
    "Colitis",
    "Dermatitis",
    "Gingivitis",
    "Tendinitis",
    "Encephalitis",
    "Myocarditis",
    "Cellulitis",
    "Emphysema",
    "Glaucoma",
    "Cirrhosis",
    "Scoliosis",
    "Fibrosis",
    "Stenosis",
    "Hemostasis",
    "Necrosis",
    "Paralysis",
    "Atrophy",
    "Edema",
    "Dysphagia",
    "Bradycardia",
    "Tachycardia",
    "Dysplasia",
    "Lordosis",
    "Kyphosis",
    "Apnea",
    "Epistaxis",
    "Hemoptysis",
    "Thrombocytopenia",
    "Leukocytosis",
    "Cholelithiasis",
    "Nephrolithiasis",
    "Hydrocephalus",
    "Synovitis",
    "Teratoma",
    "Diplopia",
    "Ptosis",
    "Mydriasis",
    "Tachypnea",
    "Dyspnea",
    "Hematemesis",
    "Melena",
    "Hematuria",
    "Myalgia",
    "Fasciculation",
    "Cyanosis",
    "Xerostomia",
    "Presbyopia",
    "Dyslexia",
    "Aphasia",
    "Dysarthria",
    "Nystagmus",
    "Strabismus",
    "Paresthesia",
    "Dyskinesia",
    "Syncope",
    "Vertigo",
    "Orthopnea",
    "Borborygmi",
    "Dysgraphia",
    "Dysphonia",
    "Hyperemesis",
    "Oliguria",
    "Polyuria",
    "Dysuria",
    "Hemianopsia",
    "Anosognosia",
    "Astereognosis",
    "Alexia",
  ]
}
