import type { WordSetData } from "../wordSetModels";

export const wordset1990sKids: WordSetData = {
  name: "1990s kids references",
  category: "entertainment",
  description: "Shows and culture recognizable by kids from the 1990s.",
  language: "en",
  words: [
    "Spongebob",
    "Pokemon",
    "Avatar The Last Airbender",
    "Rugrats",
    "Power Rangers",
    "Hey Arnold!",
    "Goosebumps",
    "Tamagotchi",
    "Furby",
    "The Fresh Prince of Bel-Air",
    "Friends",
    "Full House",
    "Boy Meets World",
    "Saved by the Bell",
    "Beavis and Butt-Head",
    "The Simpsons",
    "Seinfeld",
    "Home Alone",
    "The Lion King",
    "Aladdin",
    "Space Jam",
    "The Matrix",
    "Titanic",
    "Pogs",
    "Beanie Babies",
    "Game Boy",
    "Super Nintendo",
    "PlayStation",
    "N64",
    "Mario Kart",
    "The Legend of Zelda: Ocarina of Time",
    "Street Fighter",
    "Mortal Kombat",
    "The Spice Girls",
    "Backstreet Boys",
    "NSYNC",
    "Britney Spears",
    "The Macarena",
    "Y2K",
    "Dial-Up Internet",
    "Blockbuster",
    "Nickelodeon",
    "MTV",
    "Cartoon Network",
    "Disney Channel",
    "Animaniacs",
    "Pinky and the Brain",
    "The Magic School Bus",
    "Johnny Bravo",
    "Dexter's Laboratory",
    "Rocket Power",
    "Blue's Clues",
    "Teletubbies",
    "Arthur",
    "Easy-Bake Oven",
    "Mood Rings",
    "Magic: The Gathering",
    "Yu-Gi-Oh!",
    "Digimon",
    "Teenage Mutant Ninja Turtles",
    "Sesame Street",
    "Sabrina the Teenage Witch",
    "The Powerpuff Girls",
    "Destiny's Child",
    "Jumanji",
    "A Bug's Life",
    "Toy Story",
    "Shrek",
    "The Little Mermaid",
    "Beauty and the Beast",
    "Mulan",
    "Hercules",
    "Tarzan",
    "Pocahontas",
    "South Park",
    "The Iron Giant",
    "The Prince of Egypt",
    "A Goofy Movie",
    "Dragon Ball Z",
    "Sailor Moon",
    "Spirited Away",
    "View-Master",
    "Capri Sun",
    "Uno",
    "Jenga",
    "Twister",
    "Etch A Sketch",
    "Magic 8-Ball",
    "Rubik's Cube",
    "Tamagotchi",
    "Furby",
    "Yo-Yo",
    "Slinky",
    "Super Soaker",
    "Nerf Blaster"
  ]
}