import type { WordSetData } from "../wordSetModels";

export const wordsetNouns: WordSetData = {
  name: "Classic Nouns",
  category: "general",
  description: "Common nouns",
  language: "en",
  words: [
    "Christmas Lights",
    "Daisy",
    "Dog",
    "Easter Egg",
    "Fire Truck",
    "Flower",
    "Guitar",
    "Ice Cream",
    "Kite",
    "Lion",
    "Monkey",
    "Pineapple",
    "Rainbow",
    "Starfish",
    "Teddy Bear",
    "Umbrella",
    "Volcano",
    "Whale",
    "Zebra",
    "Apple",
    "Balloon",
    "Cat",
    "Elephant",
    "Fish",
    "Giraffe",
    "House",
    "Iceberg",
    "Jellyfish",
    "Kangaroo",
    "Lemon",
    "Mountain",
    "Notebook",
    "Octopus",
    "Penguin",
    "Robot",
    "Sailboat",
    "Train",
    "Whistle",
    "Bike",
    "Cactus",
    "Dolphin",
    "Eggplant",
    "Fireworks",
    "Grapes",
    "Hedgehog",
    "Igloo",
    "Jack-o'-lantern",
    "Kettle",
    "Lighthouse",
    "Mushroom",
    "Ninja",
    "Ostrich",
    "Piano",
    "Raccoon",
    "Sunglasses",
    "Telescope",
    "Ukulele",
    "Violin",
    "Yacht",
    "Zipper",
    "Banana",
    "Candle",
    "Dragon",
    "Envelope",
    "Fan",
    "Gum",
    "Hammer",
    "Ice Skates",
    "Jacket",
    "Keychain",
    "Laptop",
    "Mug",
    "Oven Mitt",
    "Pillow",
    "Rug",
    "Socks",
    "T-shirt",
    "Vase",
    "Waffle",
    "Yarn",
    "Zucchini",
    "Acorn",
    "Ball",
    "Eagle",
    "Frog",
    "Guitar Pick",
    "Hammock",
    "Jigsaw Puzzle",
    "Lollipop",
    "Nail Polish",
    "Parachute",
    "Rugby Ball",
    "Saddle",
    "Telescope Lens",
    "Van",
    "Whisk",
    "Zebra Crossing",
    "Airplane",
    "Basketball",
    "Couch",
    "Dinosaur",
    "Egg",
    "Flute",
    "Glasses",
    "Helicopter",
    "Jelly",
    "Ladder",
    "Mango",
    "Orange",
    "Pasta",
    "Spoon",
    "Towel",
  ]
}
