import type { WordSetData } from "../wordSetModels";

export const wordsetEconomics: WordSetData = {
  name: "Economics Terms",
  category: "sciences",
  description: "Common terms used in economics.",
  language: "en",
  words: [
    "ROI",
    "GDP",
    "Inflation",
    "Supply and Demand",
    "Market Equilibrium",
    "Fiscal Policy",
    "Monetary Policy",
    "Opportunity Cost",
    "Elasticity",
    "Market Failure",
    "Externalities",
    "Consumer Surplus",
    "Producer Surplus",
    "Trade Deficit",
    "Trade Surplus",
    "Capital Goods",
    "Consumer Goods",
    "Labor Market",
    "Price Ceiling",
    "Price Floor",
    "Business Cycle",
    "Recession",
    "Depression",
    "Boom",
    "Stagflation",
    "Hyperinflation",
    "Deflation",
    "Reflation",
    "Interest Rate",
    "Exchange Rate",
    "Tariff",
    "Subsidy",
    "Quota",
    "Bureaucracy",
    "Privatization",
    "Globalization",
    "Outsourcing",
    "E-commerce",
    "Cryptocurrency",
    "Crowdfunding",
    "Venture Capital",
    "Angel Investor",
    "IPO",
    "Stock Market",
    "Bond Market",
    "Derivatives",
    "Hedge Fund",
    "Mutual Fund",
    "Index Fund",
    "Bull Market",
    "Bear Market",
    "Liquidity",
    "Diversification",
    "Asset Allocation",
    "Risk Management",
    "Credit Default Swap",
    "Securitization",
    "Quantitative Easing",
    "Fiscal Cliff",
    "Austerity",
    "Keynesian Economics",
    "Supply-Side Economics",
    "Behavioral Economics",
    "Nudge Theory",
    "Game Theory",
    "Pareto Efficiency",
  ]
}